# 最初にgh-pagesライブラリが必要
prepare:
	npm install
	npm i gh-pages

# public/buildディレクトリの内容を再構成する。
build:
	npm run build

# それをgithub pagesのページとしてdeployする。
deploy-gh-pages:
	node ./gh-pages.js


# https://www.devsamples.com/javascript/svelte/deploy-svelte-app-gh-pages
# これでうまくいくはず。
# APIのほうは別に設けるしかない。いずれはそれも外部クラウド上に作るのだろう。

