# public/buildディレクトリの内容を再構成する。
# public以下のファイルだけで完全に動作する。
build:
	npm run build


# 最初にgh-pagesライブラリが必要
prepare:
	npm install
	npm i gh-pages


inspect:
	open ../API/public/index.html

# それをgithub pagesのページとしてdeployする。
# deploy-gh-pages:
# 	node ./gh-pages.js

# UIの試行は、make inspectでローカルで確認できるので、UIの改良はやりやすい。
